name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  i18n:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/i18n.yml
    secrets: inherit

  build:
    needs: [lint]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  artifact:
    if: github.event_name == 'pull_request'
    needs: [build]
    uses: ./.github/workflows/artifact.yml
    with:
      dist-artifact: ${{ needs.build.outputs.dist-artifact }}
    secrets: inherit

  docker:
    if: github.event_name == 'pull_request'
    needs: [build, artifact]
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/docker.yml
    with:
      dist-artifact: ${{ needs.build.outputs.dist-artifact }}
      artifact-url: ${{ needs.artifact.outputs.artifact-url }}
    secrets: inherit
