name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: nrwl/nx-set-shas@v5

      - name: Lint affected
        if: github.event_name == 'pull_request'
        run: pnpm run lint

      - name: Lint all
        if: github.ref_name == 'main'
        run: pnpm run lint:all
